### ISSUE TITLE
Zero-Sum Bank mode + inflation

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#19]
Add suppot for Zero-Sum bank mode + inflation

1. In zero-sum bank mode the price paid by player for an item is distributed evenly amongst all other players (excluding payer)
2. Inflation is understood as an additional static value given to other players

**Comment by Sah-kage** [comment]
In zero-sum bank mode the price paid by player for an item is distributed evenly amongst all other players (*including* payer)
Inflation is understood as an additional static value given to other players - there is not inflation with Zero-Sum.

Zero-sum DKP means that DKP is distributed based on the value of items that drop. All members in a zero-sum DKP start with a score of 0. When an item is given to a raid member, they have to pay for it in DKP (going negative if necessary). These DKP spent are immediately distributed among all the raid members. Thus the amount of DKP, i.e. the sum of all members in the system, is always zero. The idea here is that inflation is impossible, since no points enter the system from the outside.

**Comment by SamMousa** [comment]
That feels like a cleaner definition than the ones in original post.
