### ISSUE TITLE
Items counciling feature

### ISSUE THREAD

**Issue by cybertr0nix** [ClassicLootManager/ClassicLootManager#224]
**Is your feature request related to a problem? Please describe.**
Add the ability / interface option to give item to a raider for a fixed price without starting auction at all.

Example 1: tank loot prio
Example 2: bis items rotation
Example 3: personal bis options (I’ve mentioned mechanics of PBIS before).

This will remove some amount of annoying announcing auctions starts / ends that we see almost every couple of minutes now in raid.

**Describe the solution you'd like**
Add item to auction as normal -> add price -> ok -> click "council loot" -> add player from raid roster -> award.
Normal "win" RW appears after.

**Comment by lantisnt** [comment]
I am very against putting this directly in the addon, since addon is focused on the DKP and auctioning systems and there is no end to the number of requests of specific changes.

What I would propose is to create a Public API that allows to handle all of those cases and create maybe some comms/helpers to make WA authors life easier.

Any thoughts @SamMousa ?

**Comment by lantisnt** [comment]
This will not be included in CLM. I highly recommend using gargul for LC features https://github.com/papa-smurf/Gargul especially that there will be integration with CLM coming.
