### ISSUE TITLE
Update release file suffix to -bc.zip to allow wowup to properly track addon releases

### ISSUE THREAD

**Issue by mikec83** [ClassicLootManager/ClassicLootManager#229]
Given curseforge blocking wowup from tracking, it would be nice if your github releases follow the wowup github requirements (https://wowup.io/guide/get-addons/overview)  by ending the TBC zip file in -bc.zip

**Comment by lantisnt** [comment]
I do not see any issue with `-bcc`.
When using `github` with wowup it supports the `-bcc` suffix for quite a while now.
If you don't want to use curseforge, CLM is uploaded to WoWInterface and WAgo AddOns also, to choose from.

**Comment by mikec83** [comment]
![image](https://user-images.githubusercontent.com/1001674/153601682-cb7fd49e-4305-4863-afbb-701e66aa2be0.png)

Ok....this is the error I saw when entering the CLM github repo into wowup.

**Comment by linaori** [comment]
Heya! I've added a summary of the issue here: https://github.com/WowUp/WowUp/issues/1107#issuecomment-1036246872

Currently the WowUp app doesn't support the content type of the zips in the latest release (`application/octet-stream`). I'm not sure how the zip was created, so if it's causing issues right now it could be fixed that way. I don't think a new release would be needed, can just re-attach the zips.
