### ISSUE TITLE
Player spec communication mechanism

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#30]
Add mechanism to request spec (and update if changed) for all profiles we have and are online or in raid (in raid more important). This will result in profile update through ledger entry.

**Comment by SamMousa** [comment]
What's the definition of a spec?

- Do we care about trees only: 0/42/18
- Or do we care about individual talents

I don't see much value in having this on the ledger, I see more values in having roles in there.
Players roles are more fixed than their specs, since I can respec easily but can't just do a role I'm not familiar with or have no gear for.
For review it's more important to know what role someone has vs what spec. (Think feral druid dps vs boomkin dps)?

**Comment by lantisnt** [comment]
1. we care about trees only
2. I don't see much value in having this on the ledger
3. only needed during auction

Thought about having this communicated as a response to ready-check or on demand but auction seems reasonable also

**Comment by lantisnt** [comment]
Completed in  #108
