### ISSUE TITLE
Error editing multipliers for dynamic item values

### ISSUE THREAD

**Issue by not-ilzan** [ClassicLootManager/ClassicLootManager#378]
While experimenting with CLM as a potential replacement EPGP managing addon for my guild I discovered an issue where it wouldn't let me set slot multipliers, tier multipliers, or even the base multiplier for the equation in dynamic item values to a decimal value less than 1 if the default value was 1 or greater OR if I had assigned a value of 1 or greater.

Example 1:
By default all the tier multipliers start with a value of 1, trying to set any to a value between 0 and 1 results in the error message listed below.

Example 2:
In the case of the EPGP WEB option the ranged slot has a default value of .5 so I can give it any value between 0 and 1 without issue until I give it a value of 1 or greater then I get the error message below.

In all cases the error message I get is "[Slot Name]: Expected ^-?%d+.?%d*$"

Additional info: A quick check also turned up that if the value is initially 0, or set to 0, it won't allow decimal values less than 1 to be assigned either.

**Comment by lantisnt** [comment]
Please check if you have put dot `.`  andvnot comma by accident `,` when typing in value. WoW doesn't like comma in numberes

**Comment by lantisnt** [comment]
No further info from user. Assuming user error.

**Comment by crimsoncoyote** [comment]
May want to address that regex pattern at some point. When a decimal point is included, at least 1 digit in front of the decimal is required because of the `+` after the first `%d`. I think that is what is happening here (I ran into this early on in CLM). Could swap the `%d+` and `%d*` in the pattern and I think that removes that requirement while keeping the intention the same.

The `.?` will also match any character so weird things like 36t2 (or a number with a comma as mentioned above) would match, even though it wouldn't be considered a valid number by wow.
