### ISSUE TITLE
Total Point Hard Cap

### ISSUE THREAD

**Issue by lantisnt** [ClassicLootManager/ClassicLootManager#50]
Add total point hard cap which should be configurable on per-roster basis.

**Comment by SamMousa** [comment]
Is this an alternative to decay?
Because decay will lead to a hard cap.

**Comment by lantisnt** [comment]
Decay introduces a soft cap. Some guilds use hard cap instead. This might be used as an alternative or in conjunction to decay

**Comment by SamMousa** [comment]
Interaction of hard cap and weekly cap needs to be intuitive.
When you are awarded DKP this affects your standings.
Your weekly gain is the sum of positive awarded DKP.

Hard cap prevents you from gaining DKP. I argue that if you hit the hard cap and therefore your (part of) a DKP award is not added to your standings, it should also not be added to your weekly gains.
If it is you get really strange situations.

Imagine this:
- Hard cap: 100DKP
- My current balance: 100DKP
- Weekly cap: 10DKP
- On time: 5DKP
- Raid end: 5DKP

Now imagine this sequence of events where there are 2 raids during the week.

# Bad behavior is rewarded 

| Event             | Value | New balance | Weekly gained |
|-------------------|-------|-------------|---------------|
| Initial           |       | 100         | 0             |
| On time         | 5     | 100         | 5             |
| Get item          | 10    | 90          | 5             |
| End of raid       | 5     | 95          | 10            |
| On time | 5     | 95          | 10            |
| End of raid       | 5     | 95          | 10            |


Here this user actively gets punished for being on time.  Instead if we don't count DKP that is discarded due to the hard cap we get a more natural solution with proper incentives.


# Good behavior is rewarded

| Event             | Value | New balance | Weekly gained |
|-------------------|-------|-------------|---------------|
| Initial           |       | 100         | 0             |
| On time         | 5     | 100         | 0             |
| Get item          | 10    | 90          | 0             |
| End of raid       | 5     | 95          | 5            |
| On time | 5     | 100          | 10            |
| End of raid       | 5     | 100          | 10            |

**Comment by lantisnt** [comment]
Agree, will rework it that way

**Comment by lantisnt** [comment]
Fixed by  #60
