### ISSUE TITLE
Decimal DKP values after Decay

### ISSUE THREAD

**Issue by crimsoncoyote** [ClassicLootManager/ClassicLootManager#80]
**Describe the bug**
After applying percentage decay, DKP can be a decimal value.

**To Reproduce**
1. Apply DKP decay to DKP value which doesn't divide evenly

**Expected behavior**
DKP should be able to be rounded to a whole number. Barring that, a workaround would be needed to grant/remove partial DKP points manually.

**AddOn and Game Version:**
CLM 0.7.0

**Comment by DanSheps** [comment]
I feel like this should be more of a optional setting where it rounds to the nearest whole.  Coming from CommunityDKP and before that MonolithDKP, there was always fractions of a whole number.

**Comment by SamMousa** [comment]
Also, we should always be rounding to a fixed number of decimals, otherwise we get into float trouble territory. Even if we want decimals we should limit it to something <= 4

**Comment by roaspeci** [comment]
After three weeks we are now at 8 Numbers behind the dot :-) rounding to 1 or 2 behind would bei nice

**Comment by lantisnt** [comment]
I'm against any form of rounding values internally @SamMousa . I would propose a configurable **display** rounding solution (which will not alter the value internally itself).
Proposed formats:
`1` (no decimals)
`0.1` (tens)
`0.01` (hundreds)

**Comment by SamMousa** [comment]
There is always rounding in floats, the question is whether we actively manage it..

**Comment by DanSheps** [comment]
I would say a reasonable approach is to only round on display, but keep the precision there for the data.

**Comment by SamMousa** [comment]
We have already decided that we always round to a fixed number of decimals. At most 5, configurable by the user.
We will round not just for display; reasoning is that rounding for display causes weird behavior.
If you see 8 DKP balance and you decay 50% you always want to see 4, not 3 because it might have been 7.5 rounded down.
(Note that the example doesn't necessarily work if we round to nearest int, but always an example can be found where the loss of information leads to unpredictable result  , from the perspective of an observer seeing just the rounded number.

**Comment by SamMousa** [comment]
Thanks for the contribution!

**Comment by lantisnt** [comment]
Fixed by #93
